### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by willw1** [ryanfb/docker_inaudible_rainbowcrack#2]
docker pull ryanfb/inaudible

gives an error about unknown file, and trying to build the image (on Docker Desktop for Mac) gives

........
Setting up libsoxr0:amd64 (0.1.2-3) ...
dpkg: unrecoverable fatal error, aborting:
 unable to fsync updated status of 'libsoxr0:amd64': Input/output error
E: Sub-process /usr/bin/dpkg returned an error code (2)
The command '/bin/sh -c apt-get update &&     apt-get install -y git ffmpeg mp4v2-utils' returned a non-zero code: 100

**Comment by ryanfb** [comment]
Both work for me (Docker Desktop 2.3.0.1 on a Mac). Try resetting your Docker to factory defaults and making sure you have the latest version installed.
